config/routes.rb
ApartmenthomelivingSampleApp::Application.routes.draw do
  root :to => 'listings#index'

  resources :listings do
    collection do
      get :search
    end
    resources :floorplans
  end
end

app/models/floorplan.rb
class Floorplan < ActiveRecord::Base
  attr_accessible :listing_id, :headline

  belongs_to :listing

end

app/models/listing.rb
require 'net/http'

class Listing < ActiveRecord::Base
  attr_accessible :id, :listing_id, :fn, :url, :image, :latitude, :longitude, :telephone, :address, :city_state_zip,
                  :pricing, :is_house, :listing_no, :floorplans_attributes

  has_many :floorplans
  accepts_nested_attributes_for :floorplans

  def self.listing_json
    uri = URI.parse("http://austin.apartmenthomeliving.com/apartments-for-rent/1-bedroom.json")
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    response = http.request(request)
    response.body
  end

  def self.parse_listing_feed(listing_json)
    apartment_data = JSON.parse(listing_json)

    listing_ids = []
    Listing.all.each do |l|
      listing_ids << l.listing_id
    end
    new_count = 0
    apartment_data.each do |ad|
      unless listing_ids.include?(ad['id'])
        listing = Listing.create!(
            :listing_id => ad['id'],
            :fn => ad['fn'],
            :url => ad['url'],
            :image => ad['image'],
            :latitude => ad['latitude'],
            :longitude => ad['longitude'],
            :telephone => ad['tel'],
            :address => ad['address'],
            :city_state_zip => ad['city_st_zip'],
            :pricing => ad['pricing'],
            :is_house => ad['ishouse'],
            :listing_no => ad['listing']
        )
        ad['floorplans'].each do |fp|
          listing.floorplans.create!(:headline => fp)
        end
        new_count += 1
      end
    end
    new_count
  end

  def self.search(search)
    if search
      find(:all, :joins => :floorplans, :conditions => ['(fn like ? or address like ? or city_state_zip like ? or pricing like ? or floorplans.headline like ?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  respond_to :html, :json
  before_filter :other_listings

  def other_listings
    @other_listings = Listing.order("updated_at DESC").take(6)
  end

  def index
    if params[:search]
      @listings = Listing.search(params[:search])
    else
      @listings = Listing.order("updated_at DESC").take(10)
    end
    @hash = populate_map @listings
    respond_with @listings
  end

  def show
    @listing = Listing.find(params[:id])
    @hash = populate_map [@listing]
    respond_with @listing
  end

  private

  def populate_map(listings)
    @hash = Gmaps4rails.build_markers(listings) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
      marker.infowindow "<a href=\"#{listing_path(listing)}\">#{listing.fn}</a>"
    end
    @hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="span12">
  <p class="footer-text"><%= link_to "Home", root_path %> | <%= link_to "ApartmentHomeLiving.com", "http://www.apartmenthomeliving.com" %></p>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  <div class="container">
    <a class="brand" href="<%= root_path %>">ApartmentHomeLiving Sample App</a>
    <ul class="nav">
      <li><a href="<%= root_path %>">Home</a></li>
    </ul>
    <%= form_tag listings_path, class: "navbar-search pull-right",  method: :get do %>
      <%= text_field_tag  :search, params[:search], class: "search-query input-medium", placeholder: "Search"  %>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApartmenthomelivingSampleApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render "layouts/header" %>
  <div class="row">
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</div>

</body>
</html>

app/views/listings/_map.html.erb
<div style='width:100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    <% if action_name=='show' %>
    handler.getMap().setZoom(15);
    <% end %>
  });
</script>

app/views/listings/_other_listings.html.erb
<p><b>Other Recently Listed 1-Bedroom:</b></p>
<% i = 0 %>
<table>
  <% 2.times do %>
    <tr>
      <% 3.times do %>
        <td>
          <p class="other-listing">
            <%= link_to image_tag(@other_listings[i].image, :class => "other-listings-image"), @other_listings[i] %><br>
            <b><%= link_to @other_listings[i].pricing, @other_listings[i] %></b>
          </p>
        </td>
        <% i += 1 %>
      <% end %>
    </tr>

  <% end %>
</table>

app/views/listings/index.html.erb
<div class="span10">
  <h3>1-Bedroom Apartments</h3>
</div>
<div class="span6">
  <% @listings.each do |listing| %>
    <div class="well">
      <div class="row">
        <div class="span2">
          <%= link_to image_tag(listing.image, :class => "index-image"), listing %>
        </div>
        <div class="span3">
          <b><%= link_to listing.pricing, listing %></b>
          <h4><%= listing.fn %></h4>
          <p>
            <%= listing.address %><br>
            <%= listing.city_state_zip %><br>
            <%= listing.telephone %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
  <%= render :partial => 'other_listings' %>
</div>
<div class="span5 well">
  <%= render :partial => 'map' %>
</div>

app/views/listings/show.html.erb
<div class="span12">
  <h3><%= @listing.fn %></h3>
</div>
<div class="span7">
  <div class="well">
    <div class="row">
      <div class="span2.5">
        <%= link_to image_tag(@listing.image), @listing.url %>
      </div>
      <div class="span3.5">
        <p>
          <%= link_to @listing.pricing, @listing.url, :class => "btn" %>
        </p>
        <h4><%= @listing.fn %></h4>
        <p>
          <%= @listing.address %><br>
          <%= @listing.city_state_zip %><br>
          <%= @listing.telephone %>
        </p>
        <p>
          <b>Other Floor Plans:</b>
          <% @listing.floorplans.each do |fp| %>
          <p>
            <%= link_to fp.headline.html_safe, @listing.url, :class => "btn" %>
          </p>
        <% end %>
        </p>
      </div>
    </div>
  </div>
  <%= render :partial => 'other_listings' %>
</div>
<div class="span4 well">
  <%= render :partial => 'map' %>
</div>